config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit,:update,:destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flats_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= form_for(@flat) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name%>
  <%= t.label :address %>
  <%= t.text_field :address %>
  <%= t.label :description %>
  <%= t.text_field :description %>
  <%= t.label :price_per_night, %>
  <%= t.number_field :price_per_night, %>
  <%= t.label :number_of_guests %>
  <%= t.number_field :number_of_guests %>
  <%= t.submit %>
<% end %>

app/views/flats/index.html.erb
<h1><strong>All our Flats</strong></h1>
<% @flats.each do |flat| %>
  <p><%= flat.name %></p>
  <p><%= flat.address %></p>
  <p><%= flat.description %></p>
  <p><%= flat.price_per_night %></p>
  <p><%= flat.number_of_guests %></p>
  <p><%= link_to "More info", flat_path(flat.id) %></p>
  <p><%= link_to "Edit", edit_flat_path(flat.id) %></p>
  <p><%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure?"}  %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# Navbar %>
    <div>
      <div class="navbar navbar-light bg-light d-flex justify-content-between">
        <%= link_to "Simple Airbnb", "/flats" %></a>
        <form class="custom-inline-form">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0 search-btn" type="submit">Search</button>
          <%= link_to new_flat_path do %>
            <button type="button" class="btn btn-outline-primary add-flat-btn">
              Add flat
            </button>
          <% end %>
        </form>
      </div>
    </div>
    <%# title %>
    <div class="card">
    <%= yield %>
  </body>
</html>